language: perl
perl:
    - "5.10"
    - "5.24"
    - "5.26"
    - "blead"
sudo: false

matrix:
    include:

        - perl: "5.24"
          env:
            - TEST_YANCY_BACKEND=sqlite:/tmp/sqlite3.db
            - TEST_ONLINE_SQLITE=sqlite:/tmp/sqlite3.db
          addons:
            apt:
              packages:
                - sqlite3
                - libdbd-sqlite3-perl
          install:
            - sqlite3 /tmp/sqlite3.db < t/share/sqlite.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install Mojo::SQLite

        - perl: "5.24"
          env:
            - TEST_YANCY_BACKEND=mysql://travis@localhost/test_yancy
            - TEST_ONLINE_MYSQL=mysql://travis@localhost/yancy_mysql_test
          services:
            - mysql
          addons:
            apt:
              packages:
                - libdbd-mysql-perl
          install:
            - mysql -u travis -e 'CREATE DATABASE yancy_mysql_test'
            - mysql -u travis -e 'CREATE DATABASE test_yancy'
            - mysql -u travis test_yancy < t/share/mysql.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install Mojo::mysql

        - perl: "5.24"
          env:
            - TEST_YANCY_BACKEND=pg://postgres@localhost/test_yancy
            - TEST_ONLINE_PG=postgres://postgres@localhost/test_backend
          services:
            - postgresql
          addons:
            postgresql: "9.5"
            apt:
              packages:
                - libdbd-pg-perl
          install:
            - createdb test_backend -U postgres
            - createdb test_yancy -U postgres
            - psql -U postgres test_yancy < t/share/pg.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install Mojo::Pg

        - perl: "5.24"
          env:
            - "TEST_YANCY_BACKEND=dbic://Local::Schema/dbi:SQLite:/tmp/sqlite3.db"
          addons:
            apt:
              packages:
                - sqlite3
          install:
            - sqlite3 /tmp/sqlite3.db < t/share/sqlite.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install DBIx::Class DBD::SQLite SQL::Translator

        - perl: "5.24"
          env: COVERAGE=1

    allow_failures:
        - perl: "blead"
        - env: COVERAGE=1

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR

install:
    - cpan-install --deps
    - cpan-install --coverage

before_script:
    - coverage-setup

script:
    - perl Makefile.PL
    - make
    - prove -bl -s $(test-files)

after_success:
    - coverage-report
